### ISSUE TITLE
Cannot run javascript target using seed run ideal:js on Apple MAC OSX

### ISSUE THREAD

**Issue by PhilAndrew** [tindzk/seed#80] opened 2020-02-14 04:09 UTC
Apple Mac OSX

using seed run ideal:js

```
ⓘ Generated JavaScript file '/Users/philip/home/projects/ideal/build/ideal.js'
✗ Feb 14, 2020 3:08:15 PM com.zaxxer.nuprocess.osx.OsxProcess start
✗ WARNING: Exception thrown from handler
✗ java.lang.RuntimeException: Invocation of posix_spawn() failed, return code: 2, last error: 0
✗ 	at com.zaxxer.nuprocess.internal.BasePosixProcess.checkReturnCode(BasePosixProcess.java:639)
✗ 	at com.zaxxer.nuprocess.osx.OsxProcess.start(OsxProcess.java:85)
✗ 	at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:34)
✗ 	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
✗ 	at bloop.exec.Forker$.$anonfun$run$6(Forker.scala:185)
✗ 	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
✗ 	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
✗ 	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
✗ 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
✗ 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
✗ 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
✗ 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
✗ 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
↪ [BSP] shutdown request received: build/shutdown
↪ BSP server cancelled, closing socket...
↪ Process terminated successfully
➜  ideal
```

**Comment by nafg** [comment] 2020-02-14 14:15
Do you have node.js installed? If not that may be why it's failing,
although the error is not clear.

**Comment by PhilAndrew** [comment] 2020-02-15 10:41
Yes except the nodejs I am using is node from graalvm. I can try a different node.

**Comment by nafg** [comment] 2020-02-16 02:29
If you type `node` in your shell and press enter does it run?

**Comment by tindzk** [comment] 2020-02-16 11:33
The JavaScript file was linked correctly, but Bloop could not run it. Does the following command work?

```shell
node /Users/philip/home/projects/ideal/build/ideal.js
```

GraalVM's JavaScript implementation may behave slightly differently.

**Comment by tindzk** [comment] 2020-05-01 16:43
I will close the issue for now since it does not seem to be caused by Seed. Bloop spawns all Node.js processes, so feel free to open an issue on its bug tracker if the problem still prevails.

**Closed by tindzk** 2020-05-01 16:43 UTC
